# Generated by Django 3.2.4 on 2022-07-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='rut',
        ),
    ]
