# Generated by Django 3.2.4 on 2022-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220708_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='rut',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='rut',
            field=models.IntegerField(default=23443),
            preserve_default=False,
        ),
    ]
