# Generated by Django 3.2.4 on 2022-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220708_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='entregaRealizada',
            field=models.CharField(max_length=2),
        ),
    ]
